name: Deploy Next.js App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image (with full dependencies)
        run: |
          docker build \
            --no-cache \
            --build-arg NODE_ENV=development \
            -t eventlamp-frontend .

      - name: Save Docker image
        run: docker save eventlamp-frontend | gzip > eventlamp-frontend.tar.gz

      - name: Copy Docker image to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: 22
          source: "eventlamp-frontend.tar.gz"
          target: "~/"

      - name: SSH into VPS and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: 22
          script: |
            docker load < ~/eventlamp-frontend.tar.gz
            docker stop eventlamp-container || true
            docker rm eventlamp-container || true
            docker run -d -p 4000:4000 --restart=always --name eventlamp-container eventlamp-frontend
