name: Deploy to VPS

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: |
            ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: |
            ${{ secrets.KNOWN_HOSTS }}
          config: |
            Host ${{ secrets.SSH_HOST }}
              HostName ${{ secrets.SSH_HOST }}
              User ${{ secrets.SSH_USER }}
              IdentityFile ~/.ssh/id_rsa
              StrictHostKeyChecking no

      - name: Deploy to VPS
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
            # Navigate to project directory
            cd /root/EventLampFrontend
            
            # Pull latest changes
            git reset --hard
            git pull origin main
            
            # Rebuild and restart containers
            docker-compose down
            docker-compose build --no-cache
            docker-compose up -d
          "
