name: Deploy Next.js App

on:
  push:
    branches:
      - main # Trigger deployment on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build and push Docker image
        run: |
          docker build -t eventlamp-frontend .
          docker save eventlamp-frontend | gzip > eventlamp-frontend.tar.gz

      - name: Copy Docker image to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: 22
          source: "eventlamp-frontend.tar.gz"
          target: "~/"

      - name: SSH into VPS and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: 22
          script: |
            # Load new Docker image
            docker load < ~/eventlamp-frontend.tar.gz

            # Stop and remove old container if exists
            docker stop eventlamp-container || true
            docker rm eventlamp-container || true

            # Remove old image (optional, to free space)
            docker rmi eventlamp-frontend || true

            # Run new container
            docker run -d -p 4000:4000 --restart=always --name eventlamp-container eventlamp-frontend
