name: Deploy Next.js App

on:
  push:
    branches:
      - main # Trigger deployment on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build and push Docker image
        run: |
          docker build -t my-nextjs-app .
          docker save my-nextjs-app | gzip > my-nextjs-app.tar.gz

      - name: Copy Docker image to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: 22
          source: "my-nextjs-app.tar.gz"
          target: "~/"

      - name: SSH into VPS and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: 22
          script: |
            docker load < ~/my-nextjs-app.tar.gz
            docker stop nextjs-container || true
            docker rm nextjs-container || true
            docker run -d -p 4000:4000 --name nextjs-container my-nextjs-app
